name = "timelink-auth-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "development"

[env.production]
name = "timelink-auth"

[env.staging]
name = "timelink-auth-staging"
