name = "timelink-backend"
compatibility_date = "2024-12-06"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://timelink.digital"
ENVIRONMENT = "production"  # "development" 또는 "production"

# D1 Database는 나중에 추가
# [[d1_databases]]
# binding = "DB"
# database_name = "timelink-db"
# database_id = ""
