// R2-free object storage for TimeLink using Cloudflare D1.
// D1 max BLOB/row is 2 MB; 1.5 MB chunks keep a safety margin.
export const D1_OBJECT_CHUNK_SIZE=1_500_000;
export const D1_MAX_OBJECT_SIZE=100*1024*1024;
type ObjectMeta={key:string;size:number;content_type:string;file_name:string;part_count:number;status:string};
export async function ensureD1Storage(db:D1Database):Promise<void>{await db.exec(`CREATE TABLE IF NOT EXISTS tl_d1_objects(object_key TEXT PRIMARY KEY,size INTEGER NOT NULL DEFAULT 0,content_type TEXT NOT NULL DEFAULT 'application/octet-stream',file_name TEXT NOT NULL DEFAULT '',part_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'complete',created_at TEXT DEFAULT (datetime('now')),updated_at TEXT DEFAULT (datetime('now')));CREATE TABLE IF NOT EXISTS tl_d1_object_parts(object_key TEXT NOT NULL,part_number INTEGER NOT NULL,data BLOB NOT NULL,size INTEGER NOT NULL,created_at TEXT DEFAULT (datetime('now')),PRIMARY KEY(object_key,part_number));CREATE INDEX IF NOT EXISTS idx_tl_d1_parts_key ON tl_d1_object_parts(object_key,part_number);`);}
export async function initD1Upload(db:D1Database,key:string,fileName:string,totalSize:number,contentType:string):Promise<void>{if(!key||key.length>300)throw new Error('잘못된 저장 키입니다.');if(totalSize<0||totalSize>D1_MAX_OBJECT_SIZE)throw new Error('무료 D1 저장 한도를 초과했습니다.');await db.prepare('DELETE FROM tl_d1_object_parts WHERE object_key=?').bind(key).run();await db.prepare(`INSERT INTO tl_d1_objects(object_key,size,content_type,file_name,part_count,status,updated_at)VALUES(?,?,?,?,0,'uploading',datetime('now'))ON CONFLICT(object_key) DO UPDATE SET size=excluded.size,content_type=excluded.content_type,file_name=excluded.file_name,part_count=0,status='uploading',updated_at=datetime('now')`).bind(key,totalSize,contentType,fileName).run();}
export async function writeD1UploadPart(db:D1Database,key:string,partNumber:number,data:Uint8Array):Promise<void>{if(data.byteLength>D1_OBJECT_CHUNK_SIZE)throw new Error('청크 크기가 저장 한도를 초과했습니다.');await db.prepare('INSERT OR REPLACE INTO tl_d1_object_parts(object_key,part_number,data,size)VALUES(?,?,?,?)').bind(key,partNumber,data,data.byteLength).run();}
export async function completeD1Upload(db:D1Database,key:string):Promise<ObjectMeta>{const meta=await getD1ObjectMeta(db,key);if(!meta)throw new Error('업로드 메타데이터가 없습니다.');const n=await db.prepare('SELECT COUNT(*) AS cnt,COALESCE(SUM(size),0) AS total FROM tl_d1_object_parts WHERE object_key=?').bind(key).first<any>();if(Number(n?.cnt||0)<=0)throw new Error('업로드 파트가 없습니다.');if(Number(n?.total||0)!==meta.size)throw new Error(`파일 크기 불일치: expected=${meta.size}, actual=${Number(n?.total||0)}`);await db.prepare("UPDATE tl_d1_objects SET part_count=?,status='complete',updated_at=datetime('now') WHERE object_key=?").bind(Number(n.cnt),key).run();return {...meta,part_count:Number(n.cnt),status:'complete'};}
export async function putD1Object(db:D1Database,key:string,data:Uint8Array,contentType='application/octet-stream',fileName=''):Promise<ObjectMeta>{if(data.byteLength>D1_MAX_OBJECT_SIZE)throw new Error('무료 D1 저장 한도(100MB)를 초과했습니다.');await initD1Upload(db,key,fileName||key,data.byteLength,contentType);let batch:D1PreparedStatement[]=[];let p=1;for(let o=0;o<data.byteLength;o+=D1_OBJECT_CHUNK_SIZE){const ch=data.slice(o,Math.min(o+D1_OBJECT_CHUNK_SIZE,data.byteLength));batch.push(db.prepare('INSERT OR REPLACE INTO tl_d1_object_parts(object_key,part_number,data,size)VALUES(?,?,?,?)').bind(key,p++,ch,ch.byteLength));if(batch.length>=40){await db.batch(batch);batch=[];}}if(batch.length)await db.batch(batch);return completeD1Upload(db,key);}
export async function getD1ObjectMeta(db:D1Database,key:string):Promise<ObjectMeta|null>{const r=await db.prepare("SELECT object_key as key,size,content_type,file_name,part_count,status FROM tl_d1_objects WHERE object_key=? AND status='complete'").bind(key).first<any>();return r?{key:String(r.key),size:Number(r.size),content_type:String(r.content_type||'application/octet-stream'),file_name:String(r.file_name||''),part_count:Number(r.part_count||0),status:String(r.status)}:null;}
export async function readD1Range(db:D1Database,key:string,start:number,length:number):Promise<Uint8Array>{const m=await getD1ObjectMeta(db,key);if(!m)throw new Error('파일 없음');const s=Math.max(0,Math.floor(start)),len=Math.max(0,Math.floor(length));if(s>=m.size||len===0)return new Uint8Array();const end=Math.min(m.size,s+len),first=Math.floor(s/D1_OBJECT_CHUNK_SIZE)+1,last=Math.floor((end-1)/D1_OBJECT_CHUNK_SIZE)+1;const rows=await db.prepare('SELECT part_number,data FROM tl_d1_object_parts WHERE object_key=? AND part_number BETWEEN ? AND ? ORDER BY part_number').bind(key,first,last).all<any>();const out=new Uint8Array(end-s);let written=0;for(const row of rows.results||[]){const b=row.data instanceof Uint8Array?row.data:new Uint8Array(row.data as ArrayBuffer),pn=Number(row.part_number),ps=(pn-1)*D1_OBJECT_CHUNK_SIZE,from=Math.max(s,ps),to=Math.min(end,ps+b.byteLength);if(to>from){out.set(b.slice(from-ps,to-ps),from-s);written+=to-from;}}if(written!==out.byteLength)throw new Error('파일 데이터가 불완전합니다.');return out;}
